app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("bases.urls")),
    path("admin/", admin.site.urls),
    path("pages/", include("paginas.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("accounts/", include("allauth.urls")),
    path("productos/", include(("productos.urls", "productos"), namespace="productos")),
    # PANEL DE ADMINISTRACIÓN
    path(
        "panel_admin/",
        include(("panel_admin.urls", "admin_dashboard"), namespace="admin_dashboard"),
    ),
]

bases/urls.py
from django.urls import path, include
from .views import *

app_name = "core"

urlpatterns = [
    # path("", primera_vista, name="primera_vista")]
    path("", HomeView.as_view(), name="home")
]

paginas/urls.py
from django.urls import path
from .views import *

app_name = "pages"
urlpatterns = [
    path("about", AboutView.as_view(), name="about"),
]

panel_admin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("dashboard/", views.dashboard_view, name="dashboard"),
]

productos/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("category/", CategoryList.as_view(), name="mark_list"),
    path("category/save", category_save, name="category_save"),
    path("category/delete/<int:pk>", category_delete, name="category_delete"),
]

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = "usuarios"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("registro/", RegistroUsuarioView.as_view(), name="registro"),
    path("login2/", CustomLoginView.as_view(), name="login2"),
]

panel_admin/models.py
from django.db import models

# Create your models here.

productos/models.py
from django.db import models


class Category(models.Model):
    descript = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.descript

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

usuarios/models.py
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.db import models
from .manager import CustomUserManager


# Create your models here.
class Usuario(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(_("Nombre de Usuario"), max_length=150)
    first_name = models.CharField(_("Nombres"), max_length=150)
    last_name = models.CharField(_("Apellidos"), max_length=150)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name"]

    def __str__(self):
        return self.email

usuarios/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "username")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "username")

bases/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import *

# Create your views here.


def primera_vista(request):
    return HttpResponse(
        "Hola mundo, <b>desde el curso de Django para profesionales</b>"
    )


class HomeView(TemplateView):
    template_name = "bases/home.html"

paginas/views.py
from django.shortcuts import render
from django.views.generic import *


class AboutView(TemplateView):
    template_name = "paginas/about.html"

panel_admin/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render


@login_required
@user_passes_test(lambda u: u.is_superuser)
def dashboard_view(request):
    return render(request, "panel_admin/dashboard.html")

productos/views.py
from django.shortcuts import render
from django.views.generic import *
from .models import *


class CategoryList(ListView):
    model = Category
    context_object_name = "obj"

    def get_template_names(self):
        if self.request.headers.get("Hx-Request") == "true":
            return ["fragments/category_fragment.html"]
        return ["panel_admin/categoria.html"]


def category_save(request):
    context = {}
    template_name = "panel_admin/category-list.html"

    if request.method == "POST":
        i = request.POST.get("id")
        d = request.POST.get("descript")

        o = Category.objects.create(descript=d)
    obj = Category.objects.all().order_by("descript")
    context["obj"] = obj

    return render(request, template_name, context)


def category_delete(request, pk):
    context = {}
    template_name = "panel_admin/category-list.html"

    o = Category.objects.filter(id=pk).first()
    o.delete()

    obj = Category.objects.all().order_by("descript")
    context["obj"] = obj

    return render(request, template_name, context)

usuarios/views.py
from django.shortcuts import render
from django.views.generic import *
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView

from .forms import CustomUserCreationForm


class CustomLoginView(LoginView):
    template_name = "usuarios/login2.html"  # asegúrate de usar tu template
    redirect_authenticated_user = True

    def get_success_url(self):
        if self.request.user.is_superuser:
            return reverse_lazy("admin_dashboard:dashboard")
        return reverse_lazy("core:home")  # o tu vista de inicio para usuarios normales


class RegistroUsuarioView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("usuarios:login")
    template_name = "usuarios/registro.html"

bases/templates/bases/home.html
{%extends "base.html"%}

{%block titulo%}
Inicio
{%endblock titulo%}

{%block contenido%}

{%include "fragments/card_start.html" with header="Bienvenido a la aplicación"%}
<h4 class="card-title">{%if user.is_authenticated%} Hola {{user.email}}{%else%} <a
        href="{% url 'usuarios:login'%}">Login</a>{%endif%}
</h4>
<p class="card-text">{%lorem 5%}</p>
{% include "fragments/docs_section.html" with titulo="Inicio" %}

<p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
    standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a
    type specimen book. It has survived not only five centuries, but also the leap
</p>

{% include "fragments/docs_section_final.html"%}

{%endblock contenido%}

paginas/templates/paginas/about.html
{%extends "base.html"%}

{%block titulo%}
Acerca de la App
{%endblock titulo%}


{%block contenido%}

{%include "fragments/card_start.html" with header="Nuestra Historia"%}

{% include "fragments/docs_section.html" with titulo="Sobre nosotros" %}

<p>
    {%lorem 5%}
</p>

{% include "fragments/docs_section_final.html"%}

{%endblock contenido%}

panel_admin/templates/fragments/category_fragment.html
<!--begin::App Content Header-->
<div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6">
                <h3 class="mb-0">DASHBOARD_ALE</h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">CATEGORÍA</li>
                </ol>
            </div>
        </div>
        <!--end::Row-->
    </div>
    <!--end::Container-->
</div>
<!--end::App Content Header-->
<!--begin::App Content-->
<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div id="frm">
                        {%include 'panel_admin/category-frm.html'%}
                    </div>
                </div>
                <div class=" col-md-6">
                    <div id="list">
                        {%include 'panel_admin/category-list.html'%}
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

panel_admin/templates/fragments/menu_admin.html
<nav class="app-header navbar navbar-expand bg-body">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Start Navbar Links-->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button">
                    <i class="bi bi-list"></i>
                </a>
            </li>
            <li class="nav-item d-none d-md-block"><a href="#" class="nav-link">Home</a></li>
            <li class="nav-item d-none d-md-block"><a href="#" class="nav-link">Contact</a></li>
        </ul>
        <!--end::Start Navbar Links-->
        <!--begin::End Navbar Links-->
        <ul class="navbar-nav ms-auto">

            <!--end::Notifications Dropdown Menu-->
            <!--begin::Fullscreen Toggle-->
            <li class="nav-item">
                <a class="nav-link" href="#" data-lte-toggle="fullscreen">
                    <i data-lte-icon="maximize" class="bi bi-arrows-fullscreen"></i>
                    <i data-lte-icon="minimize" class="bi bi-fullscreen-exit" style="display: none"></i>
                </a>
            </li>
            <!--end::Fullscreen Toggle-->
            <!--begin::User Menu Dropdown-->
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">

                    <span class="d-none d-md-inline"> {%if user.is_authenticated%}
                        {{user.first_name}} {{user.last_name}}{%endif%}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                    <!--begin::User Image-->
                    <li class="user-header text-bg-primary">

                        <p>
                            {%if user.is_authenticated%}Hola {{user.first_name}}{%endif%}

                        </p>
                    </li>
                    <!--end::User Image-->
                    <!--begin::Menu Body-->

                    <!--end::Menu Body-->
                    <!--begin::Menu Footer-->
                    <li class="user-footer">

                        <form method="POST" action="{% url 'usuarios:logout'%}">
                            {%csrf_token%}
                            <button type="submit" class="btn btn-default btn-flat float-end"
                                style="cursor: pointer;">Salir</button>
                        </form>

                    </li>
                    <!--end::Menu Footer-->
                </ul>
            </li>
            <!--end::User Menu Dropdown-->
        </ul>
        <!--end::End Navbar Links-->
    </div>
    <!--end::Container-->
</nav>

panel_admin/templates/fragments/menu_vertical.html
<aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark">
    <!--begin::Sidebar Brand-->
    <div class="sidebar-brand">
        <!--begin::Brand Link-->
        <a href="./index.html" class="brand-link">
            <!--begin::Brand Image-->
            <img src="../../static/panel_admin/dist/assets/img/AdminLTELogo.png" alt="AdminLTE Logo"
                class="brand-image opacity-75 shadow" />
            <!--end::Brand Image-->
            <!--begin::Brand Text-->
            <span class="brand-text fw-light">AdminLTE 4</span>
            <!--end::Brand Text-->
        </a>
        <!--end::Brand Link-->
    </div>
    <!--end::Sidebar Brand-->
    <!--begin::Sidebar Wrapper-->
    <div class="sidebar-wrapper">
        <nav class="mt-2">
            <!--begin::Sidebar Menu-->
            <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">

                <li class="nav-header">DOCUMENTATIONS</li>
                <li class="nav-item">
                    <a href="#" class="nav-link" hx-get="{%url 'productos:mark_list'%}" hx-trigger="click"
                        hx-target="#body" hx-push-url="true" style="cursor:pointer;">
                        <i class="nav-icon bi bi-download"></i>
                        <p>Categorías</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="./docs/layout.html" class="nav-link">
                        <i class="nav-icon bi bi-grip-horizontal"></i>
                        <p>Layout</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="./docs/color-mode.html" class="nav-link">
                        <i class="nav-icon bi bi-star-half"></i>
                        <p>Color Mode</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon bi bi-ui-checks-grid"></i>
                        <p>
                            Components
                            <i class="nav-arrow bi bi-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="./docs/components/main-header.html" class="nav-link">
                                <i class="nav-icon bi bi-circle"></i>
                                <p>Main Header</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./docs/components/main-sidebar.html" class="nav-link">
                                <i class="nav-icon bi bi-circle"></i>
                                <p>Main Sidebar</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon bi bi-filetype-js"></i>
                        <p>
                            Javascript
                            <i class="nav-arrow bi bi-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="./docs/javascript/treeview.html" class="nav-link">
                                <i class="nav-icon bi bi-circle"></i>
                                <p>Treeview</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="./docs/browser-support.html" class="nav-link">
                        <i class="nav-icon bi bi-browser-edge"></i>
                        <p>Browser Support</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="./docs/how-to-contribute.html" class="nav-link">
                        <i class="nav-icon bi bi-hand-thumbs-up-fill"></i>
                        <p>How To Contribute</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="./docs/faq.html" class="nav-link">
                        <i class="nav-icon bi bi-question-circle-fill"></i>
                        <p>FAQ</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="./docs/license.html" class="nav-link">
                        <i class="nav-icon bi bi-patch-check-fill"></i>
                        <p>License</p>
                    </a>
                </li>

            </ul>
            <!--end::Sidebar Menu-->
        </nav>
    </div>
    <!--end::Sidebar Wrapper-->
</aside>

panel_admin/templates/panel_admin/categoria.html
{% extends 'panel_admin/base_adminlte.html' %}
{% block title %}Dashboard{% endblock %}
{% block contenido %}
<main class="app-main">
    {% include 'fragments/category_fragment.html' %}
</main>
{% endblock contenido%}

panel_admin/templates/panel_admin/category-frm.html
<div class="card card-primary card-outline mb-4">
    <!--begin::Header-->
    <div class="card-header">
        <div class="card-title">Formulario | Categorias</div>
    </div>
    <!--end::Header-->
    <!--begin::Form-->
    <form hx-post="{%url 'productos:category_save'%} " hx-target="#list" method="POST">
        <!--begin::Body-->
        <div class="card-body">
            <div class="mb-6">
                <label for="id" class="form-label">Id</label>
                <input type="text" class="form-control" id="id" aria-describedby="idhelp" name="id" placeholder="id"
                    readonly value="{{obj.id}}" />
                <small id="idhelp" class="form-text text-muted">Id de la categoria</small>
            </div>
            <div class="mb-6">
                <label for="descript" class="form-label">Descripcion</label>
                <input type="text" class="form-control" id="descript" aria-describedby="idhelp" name="descript"
                    placeholder="Descripcion" value="{{obj.descript}}" />
                <small id="descripthelp" class="form-text text-muted">Descripcion</small>
            </div>

        </div>
        <!--end::Body-->
        <!--begin::Footer-->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="button" class="btn btn-primary" hx-get="{%url 'productos:mark_list'%}"
                hx-target="#body">Limpiar</button>
        </div>
        <!--end::Footer-->
    </form>
    <!--end::Form-->
</div>

panel_admin/templates/panel_admin/category-list.html
{%if obj%}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Tabla de Categorías</h3>
                    </div>
                    <div class="card-body">

                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripcion</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {%for o in obj%}
                                <tr>
                                    <td>{{o.id}}</td>
                                    <td>{{o.descript}}</td>
                                    <td>
                                        <i class="bi bi-trash3" style="cursor:pointer;"
                                            hx-delete="{%url 'productos:category_delete' o.id%}" hx-target="#list"
                                            hx-confirm="¿Está seguro que desea eliminar el registro?"></i>
                                        <i class="bi bi-pencil-square" style="cursor:pointer;"></i>
                                    </td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{%else%}
<p>No hay registros</p>
{%endif%}

panel_admin/templates/panel_admin/dashboard.html
{% extends 'panel_admin/base_adminlte.html' %}
{% block title %}Dashboard{% endblock %}
{% block contenido %}
<main class="app-main">
    <!--begin::App Content Header-->
    <div class="app-content-header">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-6">
                    <h3 class="mb-0">DASHBOARD_ALE</h3>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-end">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                    </ol>
                </div>
            </div>
            <!--end::Row-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::App Content Header-->
    <!--begin::App Content-->
    <div class="content-wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-lg-6 col-6">
                        <!-- small box -->
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>
                                    a
                                </h3>

                                <p>Usuarios conectados</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>

                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-6 col-6">
                        <!-- small box -->
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>
                                    as
                                </h3>

                                <p>Temas Creados</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a href="#" class="small-box-footer">Más información <i
                                    class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-6 col-6">
                        <!-- small box -->
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>
                                    wq
                                </h3>

                                <p>Sesiones Creadas</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="#" class="small-box-footer">Más información <i
                                    class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-6 col-6">
                        <!-- small box -->
                        <div class="small-box bg-danger">
                            <div class="inner">
                                <h3>
                                    qw
                                </h3>

                                <p>Recursos Disponibles</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pie-graph"></i>
                            </div>
                            <a href="#" class="small-box-footer">Más información <i
                                    class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                </div>

            </div><!-- /.container-fluid -->
        </section>
    </div>
</main>
{% endblock contenido%}

templates/base.html
{%load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %} App Web para la Pastelería D'Luciana {%endblock titulo%}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap_litera.min.css'%}">
    <!-- <link rel="stylesheet" href="{% static 'css/app.css' %}"> -->
</head>

<body id="body">
    <!-- {% include "fragments/header.html" %} -->
    <!--Barra de navegación-->
    {% include "fragments/menu.html"%}
    <!--Fin de barra de navegación-->
    <div class="container">
        <div class="row">
            <div class="container sm">

                {%block contenido%}

                {%endblock contenido%}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.4/umd/popper.min.js"
        integrity="sha512-+Tn2V/oN9O/kiaJg/1o5bETqyS35pMDJzkhkf8uvCzxmRox69AsWkSpBSMEGEe4EZp07Nunw712J3Xvh5Tti0w=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- <script src="https://unpkg.com/htmx.org@2.0.4"
        integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
        crossorigin="anonymous"></script> -->
    <script src="{% static 'js/htmx.js'%}"></script>
</body>

</html>

templates/fragments/card_start.html
<div class="card mb-3">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h3 class="card-header">{{header|default:"NADA"}}</h3>

                <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200"
                    aria-label="Placeholder: Image cap" focusable="false" role="img"
                    preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180"
                    style="font-size:1.125rem;text-anchor:middle">
                    <rect width="100%" height="100%" fill="#868e96"></rect>
                    <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text>
                </svg>
            </div>
        </div>
    </div>
</div>

templates/fragments/docs_section.html
<div class="bs-docs-section">

    <div class="row">
        <div class="col-lg-12">
            <h1>{{titulo|default:"Titulo de la página"}}</h1>
        </div>
    </div>

templates/fragments/docs_section_final.html
</div>

templates/fragments/menu.html
{%load socialaccount%}
{%providers_media_js%}

<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Pastelería D'Luciana</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <div class="nav-link" hx-get="{% url 'core:home' %}" hx-push-url="true" hx-trigger="click"
                        hx-target="#body" hx-swap="outerHTML" style="cursor: pointer;">Inicio</div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Registrar</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                        aria-haspopup="true" aria-expanded="false" style="cursor: pointer;">Catálogos</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Marcas</a>
                        <a class="dropdown-item" href="#">Modelos</a>
                        <a class="dropdown-item" href="#">Vehículos</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
                <li class="nav-item">
                    <div class="nav-link" hx-get="{% url 'pages:about' %}" hx-push="true" hx-trigger="click"
                        hx-target="#body" hx-swap="outerHTML" style="cursor: pointer;">Nosotros</div>
                </li>
            </ul>

            <div class="d-flex gap-2">
                {% if user.is_authenticated %}
                <form method="POST" action="{% url 'usuarios:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" style="cursor: pointer;">Salir</button>
                </form>
                {% else %}
                <!-- <div class="nav-link p-0" style="cursor: pointer;" hx-get="{% url 'usuarios:login' %}"
                    hx-push-url="true" hx-trigger="click" hx-target="#body" hx-swap="outerHTML">
                    <button type="button" class="btn btn-danger">Login</button>
                </div> -->
                <div class="nav-link p-0" style="cursor: pointer;" hx-get="{% url 'usuarios:login2' %}"
                    hx-push-url="true" hx-trigger="click" hx-target="#body" hx-swap="outerHTML">
                    <button type="button" class="btn btn-danger">Login</button>
                </div>
                <div class="nav-link p-0" style="cursor: pointer;" hx-get="{% url 'usuarios:registro' %}"
                    hx-push-url="true" hx-trigger="click" hx-target="#body" hx-swap="outerHTML">
                    <button type="button" class="btn btn-danger">Registrar</button>
                </div>

                <div class="nav-link p-0" style="cursor: pointer;" hx-get="{% provider_login_url 'google' %}"
                    hx-push-url="true" hx-trigger="click" hx-target="#body" hx-swap="outerHTML">
                    <button type="button" class="btn btn-danger">Google</button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

usuarios/templates/usuarios/login2.html
{%extends "base.html"%}
{%load crispy_forms_tags%}
{%block titulo%}
Login
{%endblock titulo%}


{%block contenido%}

{%include "fragments/card_start.html" with header="Ingrese Credenciales de Acceso"%}
<form method="post">
    {%csrf_token%}
    {{form|crispy}}
    <button type="submit" class="btn btn-success">Acceder</button>
</form>
{% include "fragments/docs_section_final.html"%}

{%endblock contenido%}

usuarios/templates/usuarios/registro.html
{%extends "base.html"%}
{%load crispy_forms_tags%}
{%block titulo%}
Registro
{%endblock titulo%}

{%block contenido%}

{%include "fragments/card_start.html" with header="Registro de Usuario"%}
<form hx-post="{%url 'usuarios:registro'%}" hx-target="#body" hx-headers='{"X-CSRFToken":"{{csrf_token}}"}'>
    {#%csrf_token%#}
    {{form|crispy}}
    <button type="submit" class="btn btn-success">Registrar</button>
</form>
{% include "fragments/docs_section_final.html"%}

{%endblock contenido%}